config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :homes
  root "homes#index"
  resources :profiles
  resources :products
  resources :carts
  resources :books
  resources :electronics
  resources :travels
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

    def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :manage, :dashboard         # allow access to dashboard
    end
    
    if user.seller_role?
      can :manage, User
    end
    
    if user.user_role?
      can :manage, :product
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # def add_item(product_id)
  #       line_item = line_items.where('product_id = ?', product_id).first
  #   if line_item
  #       # increase the quantity of product in cart
  #       line_item.quantity + 1
  #       save
  #   else
  #       # product does not exist in cart
  #       product = Product.find(product_id)
  #       line_items << product
  #   end
  #   save
  # end

  # def total_price
  #   line_items.to_a.sum(&:full_price)
  # end
  def sub_total
  sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
  return sum
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    self.quantity * self.product.price
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :photo
    belongs_to :user, optional: true
    # belongs_to :categories
    has_many :line_items, dependent: :destroy
    # enum :category, [:toys, :electronics, :food]


    # validates :description, length: { minimum: 2, message: "Description must be min.2 letter"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :send_admin_mail
  
  def name
  "#{first_name} #{last_name}"
  end

  def send_admin_mail
    UserMailer.send_welcome_email(self).deliver_later
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end
end

app/controllers/carts_controller.rb
# class CartsController < ApplicationController
#   def show
#    @cart = current_cart
#   end
# end

class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/electronics_controller.rb
class ElectronicsController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    # @slideshowImage = ImageSlideShow.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :find_product, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!,except:[:index]

    def index
      @products = Product.all.order(created_at: :desc)
      
      #@posts = Post.description
    end
    
    def new 
      @product = Product.new
    end
    
    def create
      @product = Product.new(product_params)

      if @product.save
        redirect_to products_path 
      else
        render "new"
      end
    end

    def show
      @product = Product.find(params[:id])
    end

    def find_product
      @product = Product.find(params[:id])
    end

    def edit
      @product = Product.find(params[:id])
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_path
    end

    def update
      @product = Product.find(params[:id])  
      if @product.update(product_params)
        redirect_to products_path
      else
        render 'edit'
      end
    end

   private
    def product_params
      params.require(:product).permit(:name, :price, :description, :photo)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :find_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
   
  end

  def show
    @profile = Profile.find(profile_params)
  end


  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)
  end

  private

  def find_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.permit(:profile).permit(:name, :summary, :birthday, :user_id)
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/electronics_helper.rb
module ElectronicsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/electronics/index.html.erb
<h1>Electronics Devices</h1>
<div class="category-box">
  <div class="category">
    <div class="category-option">
      <img src="https://rukminim1.flixcart.com/image/200/200/kokdci80/dslr-camera/v/e/x/z-24-200mm-z5-nikon-original-imag2zuekuxgxsgg.jpeg?q=70" alt=""></a>
      <span>Camera</span>
      <%= link_to "Add to cart", carts_path() %>
      <%= link_to "Buy now", cart_path(:products) %>
      <div class="_8VNy32">
        <div class="_25b18c">
          <div class="_30jeq3">₹5000</div>
        </div>
      </div>
    </div>
    <div class="category-option">
      <img src="https://rukminim1.flixcart.com/image/200/200/keyboard/laptop-keyboard/p/7/9/logitech-mk220-original-imaescsjvphz6yyq.jpeg?q=70" alt=""></a>
      <span>Keyboards</span>
      <%= link_to "Add to cart", carts_path() %>
      <%= link_to "Buy now", cart_path(:products) %>
      <div class="_30jeq3">₹2000</div>
   </div>
    <div class="category-option">
      <img src="https://rukminim1.flixcart.com/image/612/612/korijrk0/mouse/j/p/k/b175-logitech-original-imag359v76rygsaf.jpeg?q=70" alt=""></a>
      <span>Wireless Mouse</span>
      <%= link_to "Add to cart", carts_path() %>
      <%= link_to "Buy now", cart_path(:products) %>
      <div class="_30jeq3">₹500</div>
    </div>
    <div class="category-option">
      <img src="https://rukminim1.flixcart.com/image/200/200/jtx9evk0/router/g/g/k/d-link-dir-819-original-imaff5yhcm7fdfjr.jpeg?q=70" alt=""></a>
			<%= link_to "Add to cart", carts_path() %>
			<%= link_to "Buy now", cart_path(:products) %>
			<div class="_30jeq3">₹500</div>
      <span>Routers</span>
    </div>
    <div class="category-option">
      <img src="https://rukminim1.flixcart.com/image/200/200/jiulk7k0/graphics-tablet/2/c/x/intuos-small-medium-no-ctl-6100wl-k0-cx-wacom-original-imaf6jy4d3afk3g3.jpeg?q=70" alt=""></a>
      <span>Graphic Card</span>
       <%= link_to "Add to cart", carts_path() %>
      <%= link_to "Buy now", cart_path(:products) %>
      <div class="_30jeq3">₹2500</div>
    </div>
  </div>
</div>