config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :homes
  root "homes#index"
  resources :profiles
  resources :products
  resources :carts
  resources :books
  resources :electronics
  resources :travels
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

    def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :manage, :dashboard         # allow access to dashboard
    end
    
    if user.seller_role?
      can :manage, User
    end
    
    if user.user_role?
      can :manage, :product
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # def add_item(product_id)
  #       line_item = line_items.where('product_id = ?', product_id).first
  #   if line_item
  #       # increase the quantity of product in cart
  #       line_item.quantity + 1
  #       save
  #   else
  #       # product does not exist in cart
  #       product = Product.find(product_id)
  #       line_items << product
  #   end
  #   save
  # end

  # def total_price
  #   line_items.to_a.sum(&:full_price)
  # end
  def sub_total
  sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
  return sum
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    self.quantity * self.product.price
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :photo
    belongs_to :user, optional: true
    # belongs_to :categories
    has_many :line_items, dependent: :destroy
    # enum :category, [:toys, :electronics, :food]


    # validates :description, length: { minimum: 2, message: "Description must be min.2 letter"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :send_admin_mail
  
  def name
  "#{first_name} #{last_name}"
  end

  def send_admin_mail
    UserMailer.send_welcome_email(self).deliver_later
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end
end

app/controllers/carts_controller.rb
# class CartsController < ApplicationController
#   def show
#    @cart = current_cart
#   end
# end

class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    # @slideshowImage = ImageSlideShow.all
  end
end

app/controllers/line_items_controller.rb
def create
  # Find associated product and current cart
  chosen_product = Product.find(params[:product_id])
  current_cart = @current_cart

  # If cart already has this product then find the relevant line_item and iterate quantity otherwise create a new line_item for this product
  if current_cart.products.include?(chosen_product)
    # Find the line_item with the chosen_product
    @line_item = current_cart.line_items.find_by(:product_id => chosen_product)
    # Iterate the line_item's quantity by one
    @line_item.quantity += 1
  else
    @line_item = LineItem.new
    @line_item.cart = current_cart
    @line_item.product = chosen_product
  end

  # Save and redirect to cart show path
  @line_item.save
  redirect_to cart_path(current_cart)
end
def destroy
  @line_item = LineItem.find(params[:id])
  @line_item.destroy
  redirect_to cart_path(@current_cart)
end 
def add_quantity
  @line_item = LineItem.find(params[:id])
  @line_item.quantity += 1
  @line_item.save
  redirect_to cart_path(@current_cart)
end

def reduce_quantity
  @line_item = LineItem.find(params[:id])
  if @line_item.quantity > 1
    @line_item.quantity -= 1
  end
  @line_item.save
  redirect_to cart_path(@current_cart)
end


private
  def line_item_params
    params.require(:line_item).permit(:quantity,:product_id, :cart_id)
  end
  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :find_product, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!,except:[:index]

    def index
      @products = Product.all.order(created_at: :desc)
      
      #@posts = Post.description
    end
    
    def new 
      @product = Product.new
    end
    
    def create
      @product = Product.new(product_params)

      if @product.save
        redirect_to products_path 
      else
        render "new"
      end
    end

    def show
      @product = Product.find(params[:id])
    end

    def find_product
      @product = Product.find(params[:id])
    end

    def edit
      @product = Product.find(params[:id])
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_path
    end

    def update
      @product = Product.find(params[:id])  
      if @product.update(product_params)
        redirect_to products_path
      else
        render 'edit'
      end
    end

   private
    def product_params
      params.require(:product).permit(:name, :price, :description, :photo)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :find_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
   
  end

  def show
    @profile = Profile.find(profile_params)
  end


  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)
  end

  private

  def find_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.permit(:profile).permit(:name, :summary, :birthday, :user_id)
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/electronics_helper.rb
module ElectronicsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/books/index.html.erb
<h1>Books</h1

<div class="category-box">
  <div class="category">
    <div class="category-option">
      <img src="https://rukminim1.flixcart.com/image/312/312/kk76wsw0/book/2/b/9/bill-gates-success-secrets-original-imafzhyryfyx2hby.jpeg?q=70" alt=""></a>
      <span>Bill Gates:Success Secret</span>
      <%= link_to "Add to cart", carts_path() %>
      <%= link_to "Buy now", cart_path(:products) %>
      <div class="_8VNy32">
        <div class="_25b18c">
          <div class="_30jeq3">₹705</div>
        </div>
      </div>
    </div>
    <div class="category-option">
      <img src="https://rukminim1.flixcart.com/image/312/312/ktketu80/regionalbooks/e/k/i/25-ki-series-25-nda-gat-mock-test-series-original-imag6vwj8mfuj63s.jpeg?q=70" alt=""></a>
      <span>25 KI Series</span>
   </div>
    <div class="category-option">
      <img src="https://rukminim1.flixcart.com/image/312/312/ksez24w0/book/d/8/b/indian-polity-for-civil-services-and-other-state-examinations-original-imag5zd3gcmsghst.jpeg?q=70" alt=""></a>
      <span>Indian Polity</span>
    </div>
    <div class="category-option">
      <img src="https://rukminim1.flixcart.com/image/300/300/l4pxk7k0/regionalbooks/i/o/l/the-answer-writing-manual-for-upsc-civil-services-exam-state-psc-original-imagfjxzjpwzbcdh.jpeg?q=90" alt=""></a>
      <span>The Answer Writing</span>
    </div>
    <div class="category-option">
      <img src="https://rukminim1.flixcart.com/image/150/150/k5e7o280/regionalbooks/z/g/g/communication-theory-b-e-b-tech-iv-semester-r-17-anna-university-original-imafz2fv3pmdjxsr.jpeg?q=70" alt=""></a>
      <span>Communication Theory</span>
    </div>
  </div>
</div>

app/views/homes/index.html.erb
<!-- category navigation -->
<div class="category-box">
  <div class="category">
    <div class="category-option">
      <a href="https://www.flipkart.com/grocery-supermart-store?marketplace=GROCERY&fm=neo%2Fmerchandising&iid=M_9a1a9876-24bf-489c-b1ad-dcec54cacfad_1_372UD5BXDFYS_MC.CBUR1Q46W5F1&otracker=hp_rich_navigation_1_1.navigationCard.RICH_NAVIGATION_Grocery_CBUR1Q46W5F1&otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L0_view-all&cid=CBUR1Q46W5F1">
      <img src="https://rukminim1.flixcart.com/flap/128/128/image/29327f40e9c4d26b.png?q=100" alt=""></a>
      <span>Grocery</span>
   </div>
    <div class="category-option">
      <a href= "https://www.flipkart.com/mobile-phones-store?fm=neo%2Fmerchandising&iid=M_9a1a9876-24bf-489c-b1ad-dcec54cacfad_1_372UD5BXDFYS_MC.ZRQ4DKH28K8J&otracker=hp_rich_navigation_2_1.navigationCard.RICH_NAVIGATION_Mobiles_ZRQ4DKH28K8J&otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_2_L0_view-all&cid=ZRQ4DKH28K8J">
      <img src="https://rukminim1.flixcart.com/flap/128/128/image/22fddf3c7da4c4f4.png?q=100" alt=""></a>
      <span>Mobiles</span>
    </div>
    <div class="category-option">
      <a href= "https://www.flipkart.com/clothing-and-accessories/topwear/pr?sid=clo,ash&p[]=facets.ideal_for%255B%255D%3DMen&p[]=facets.ideal_for%255B%255D%3Dmen&otracker=categorytree&fm=neo%2Fmerchandising&iid=M_9a1a9876-24bf-489c-b1ad-dcec54cacfad_1_372UD5BXDFYS_MC.6XNZG1FYFBZT&otracker=hp_rich_navigation_1_1.navigationCard.RICH_NAVIGATION_Fashion~Men%2527s%2BTop%2BWear_6XNZG1FYFBZT&otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L1_view-all&cid=6XNZG1FYFBZT">
      <img src="https://rukminim1.flixcart.com/flap/128/128/image/82b3ca5fb2301045.png?q=100" alt=""></a>
      <span>Fashion</span>
    </div>
    <div class="category-option">
      <!-- <a href= "https://www.flipkart.com/elec-b2b-store?fm=neo%2Fmerchandising&iid=M_9a1a9876-24bf-489c-b1ad-dcec54cacfad_1_372UD5BXDFYS_MC.1B9DW42USMK1&otracker=hp_rich_navigation_2_1.navigationCard.RICH_NAVIGATION_Electronics~Electronics%2BGST%2BStore_1B9DW42USMK1&otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_2_L1_view-all&cid=1B9DW42USMK1"> -->
      <img src="https://rukminim1.flixcart.com/flap/128/128/image/69c6589653afdb9a.png?q=100" alt="" usemap="#workmapy"></a>
      <map name="workmapy">
        <area shape="default" coords="34,44,270,350" alt="Travels" href="electronics#index.html">
      </map>  
      <span>Electronics</span>
    </div>
    <div class="category-option">
      <a href= "https://www.flipkart.com/kitchen-cookware-serveware/pr?count=40&otracker=CLP_lhs&sid=upp&fm=neo%2Fmerchandising&iid=M_9a1a9876-24bf-489c-b1ad-dcec54cacfad_1_372UD5BXDFYS_MC.4EYWRCGS3WUT&otracker=hp_rich_navigation_4_1.navigationCard.RICH_NAVIGATION_Home~Kitchen%2B%2526%2BDining_4EYWRCGS3WUT&otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_4_L1_view-all&cid=4EYWRCGS3WUT">
      <img src="https://rukminim1.flixcart.com/flap/128/128/image/ee162bad964c46ae.png?q=100" alt=""></a>
      <span>Home</span>
    </div>
    <div class="category-option">
      <a href= "https://www.flipkart.com/tvs-and-appliances-new-clp-store?fm=neo%2Fmerchandising&iid=M_9a1a9876-24bf-489c-b1ad-dcec54cacfad_1_372UD5BXDFYS_MC.LO4IWVHA61BX&otracker=hp_rich_navigation_6_1.navigationCard.RICH_NAVIGATION_Appliances_LO4IWVHA61BX&otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_6_L0_view-all&cid=LO4IWVHA61BX">
      <img src="https://rukminim1.flixcart.com/flap/128/128/image/0ff199d1bd27eb98.png?q=100" alt=""></a>
       <span>Appliances</span>
    </div>
    <div class="category-option">
      

      <img src="https://rukminim1.flixcart.com/flap/128/128/image/71050627a56b4693.png?q=100" alt="" usemap="#workmapi"></a>
      <map name="workmapi">
          <area shape="default" coords="34,44,270,350" alt="Travels" href="products#show.html">
      </map>
      <span>Travel</span>
    </div>
    <div class="category-option">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSs-rW6aHzuFiTKfkFUckPCEj_D5WrVTUYFg&usqp=CAU" alt="" usemap="#workmap">      
        <map name="workmap">
          <area shape="default" coords="34,44,270,350" alt="Books" href="books#index.html">
        </map>
        <%#= link_to "Books",books_path() %>
       <span>Books</span>
    </div>
  </div>
 </div>
 <button type="button"
onclick="document.getElementById('demo').innerHTML = Date()">
Display the Current time-date</button>

<p id="demo"></p>

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 15%;
  margin-bottom: 16px;
  padding: 0 5px;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
}

.container {
  padding: 0 16px;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: yellowgreen;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #555;
}
</style>
</head>
<body>

<h2>Products Grid</h2>
<br>
<div class="row">
  <div class="column">
    <div class="card">
      <img src="https://rukminim1.flixcart.com/image/612/612/kiqbma80-0/memory-card/microsdhc/u/r/e/sdsdqm-032g-b35-sdsqbnn-032g-go31n-sandisk-original-imafygbgjupug9gn.jpeg?q=70" style="width:58%">
      <div class="container">
        <h2>HD Card</h2>
        <p class="title">Price $5.99</p>
        <p>hdcard@fcart.com</p>
        <p><button class="button">Add to cart</button></p>
        <%= button_to "Buy now", cart_path(:products) %>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card">
      <img src="https://rukminim1.flixcart.com/image/200/200/water-purifier/9/8/f/-1000x1000-imaemtfnd5yvrx98.jpeg?q=90" style="width:43%">
      <div class="container">
        <h2>Bottle Jar</h2>
        <p class="title">Price $10.99</p>
        <p>bottle@fcart.com</p>
        <p><button class="button">Add to cart</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="https://rukminim1.flixcart.com/image/612/612/l1pc3gw0/shopsy-mobile-holder/i/m/g/stand-height-adjustable-and-angle-adjustable-telescopic-florican-original-imagd7knfxhuggyc.jpeg?q=70" style="width:44%">
      <div class="container">
        <h2>Mobile Stand</h2>
        <p class="title">Price $10.55</p>
        <p>mobile@fcart.com</p>
        <p><button class="button">Add to cart</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="https://rukminim1.flixcart.com/image/612/612/xif0q/pump/2/l/h/air-pump-double-action-1556a-strauss-original-imaggarbu6fsmxe6.jpeg?q=70" style="width:30%">
      <div class="container">
        <h2>Bycycle Air Pump</h2>
        <p class="title">Price $10.55</p>
        <p>bycycle@fcart.com</p>
        <p><button class="button">Add to cart</button></p>
      </div>
    </div>
  </div>  
    <div class="column">
    <div class="card">
      <img src="https://rukminim1.flixcart.com/image/612/612/kwwfte80/helmet/x/d/h/sba-7-7wings-isi-certified-flip-up-helmet-for-men-and-women-1-original-imag9hfqgu6gsjjc.jpeg?q=70" style="width:40%">
      <div class="container">
        <h2>Helmet</h2>
        <p class="title">Price $10.55</p>
        <p>helmet@fcart.com</p>
        <p><button class="button">Add to cart</button></p>
      </div>
    </div>
  </div>  
      <div class="column">
    <div class="card">
      <img src="https://rukminim1.flixcart.com/image/612/612/ktq4l8w0/ceiling-lamp/m/3/g/1-7-5-3-50-mini-fan-blade-5-led-panels-viraan-original-imag7y7brjphfs5g.jpeg?q=70" style="width:70%">
      <div class="container">
        <h2>LED Bulb</h2>
        <p class="title">Price $10.55</p>
        <p>ledbulb@fcart.com</p>
        <p><button class="button">Add to cart</button></p>
      </div>
    </div>
  </div>  
</div>

<div class="row">
  <div class="column">
    <div class="card">
      <img src="https://rukminim1.flixcart.com/image/612/612/ksxjs7k0/mouse/n/5/l/zeb-rise-zebronics-original-imag6duduz5gvhhz.jpeg?q=70"  style="width:75%">
      <div class="container">
        <h2>Mouse</h2>
        <p class="title">Price $5.99</p>
        <p>mouse@fcart.com</p>
        <p><button class="button">Add to cart</button></p>
      </div>
    </div>
  </div>
  
  <div class="column">
    <div class="card">
      <img src= "https://rukminim1.flixcart.com/image/612/612/kynb6vk0/monitor/1/n/s/lf22t354fhwxxl-full-hd-22-lf22t354fhwxxl-samsung-original-imagats2rjbg9uhv.jpeg?q=70" style="width:53%">
      <div class="container">
        <h2>L C D</h2>
        <p class="title">Price $5.99</p>
        <p>lcd@fcart.com</p>
        <p><button class="button">Add to cart</button></p>
      </div>
    </div>
  </div>
    <div class="column">
    <div class="card">
      <img src="https://rukminim1.flixcart.com/image/612/612/xif0q/painting/n/g/v/17-3-cw-146p-cw-crafts-world-original-imagm8featsfwzdg.jpeg?q=70" style="width:43%">
      <div class="container">
        <h2>Shiva Painting</h2>
        <p class="title">Price $5.99</p>
        <p>painting@fcart.com</p>
        <p><button class="button">Add to cart</button></p>
      </div>
    </div>
  </div>
   <div class="column">
    <div class="card">
      <img src="https://rukminim1.flixcart.com/image/612/612/xif0q/t-shirt/z/g/o/l-jc22-hd-fs-black-jmc-pckt-jump-cuts-original-imagg3yxshqtv3dk.jpeg?q=70"  style="width:30%">
      <div class="container">
        <h2>T-Shirt</h2>
        <p class="title">Price $5.99</p>
        <p>tshirt@fcart.com</p>
        <p><button class="button">Add to cart</button></p>
      </div>
    </div>
  </div>
   <div class="column">
    <div class="card">
      <img src= "https://rukminim1.flixcart.com/image/612/612/kjrh2fk0/data-cable/lightning-cable/4/l/e/por-1080-konnect-l-portronics-original-imafz9hxhyggzpgw.jpeg?q=70" style="width:34%">
      <div class="container">
        <h2>Charging Card</h2>
        <p class="title">Price $5.99</p>
        <p>chargingcard@fcart.com</p>
        <p><button class="button">Add to cart</button></p>
      </div>
    </div>
  </div>
  <div class="column">
    <div class="card">
      <img src="https://rukminim1.flixcart.com/image/612/612/krdtlzk0/cycle/0/u/w/tribe-20t-matte-black-and-fluorescent-yellow-20-12-lifelong-original-imag56jkz6xhwahf.jpeg?q=70"  style="width:60%">
      <div class="container">
        <h2>Cycle</h2>
        <p class="title">Price $100.99</p>
        <p>cycle@fcart.com</p>
        <p><button class="button">Add to cart</button></p>
      </div>
    </div>
  </div>
</div>    
</body>
</html>

app/views/profiles/index.html.erb
<h3>Hello Techwinners</h3><br>
<h3>Welcome to Flipkart-Portal</h3>
<%#= image_tag asset_url('Bgimages.jpeg') %>

<div class="profilepage"> 
<h4>Login by</h4><br/>
<h5>
<% if user_signed_in? %>
Name: <%= current_user.name %><br/><br/>
Email-Id: <%= current_user.email %><br/><br/>
Birthday: <%= current_user.date_of_birth %><br/><br/>
Phone No.:<%= current_user.phone_number%><br/><br/>
Gender.:<%= current_user.gender%></h5>
<% end %>
</div>