config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :homes
  root "homes#index"
  resources :profiles
  resources :products
  resources :carts
  resources :books
  resources :electronics
  resources :travels
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

    def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :manage, :dashboard         # allow access to dashboard
    end
    
    if user.seller_role?
      can :manage, User
    end
    
    if user.user_role?
      can :manage, :product
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # def add_item(product_id)
  #       line_item = line_items.where('product_id = ?', product_id).first
  #   if line_item
  #       # increase the quantity of product in cart
  #       line_item.quantity + 1
  #       save
  #   else
  #       # product does not exist in cart
  #       product = Product.find(product_id)
  #       line_items << product
  #   end
  #   save
  # end

  # def total_price
  #   line_items.to_a.sum(&:full_price)
  # end
  def sub_total
  sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
  return sum
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    self.quantity * self.product.price
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :photo
    belongs_to :user, optional: true
    # belongs_to :categories
    has_many :line_items, dependent: :destroy
    # enum :category, [:toys, :electronics, :food]


    # validates :description, length: { minimum: 2, message: "Description must be min.2 letter"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :send_admin_mail
  
  def name
  "#{first_name} #{last_name}"
  end

  def send_admin_mail
    UserMailer.send_welcome_email(self).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # load_and_authorize_resource
   # before_action :authenticate_user!
 protect_from_forgery with: :exception
 before_action :configure_permitted_parameters, if: :devise_controller?
 before_action :current_cart


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :first_name, :last_name,:gender,:user_name, :date_of_birth,:phone_number)
    end
  end


  private
  def current_cart
    if session[:cart_id]
      cart = Cart.find_by(:id => session[:cart_id])
      if cart.present?
        @current_cart = cart
      else
        session[:cart_id] = nil
      end
    end

    if session[:cart_id] == nil
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end
end

app/controllers/carts_controller.rb
# class CartsController < ApplicationController
#   def show
#    @cart = current_cart
#   end
# end

class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    # @slideshowImage = ImageSlideShow.all
  end
end

app/controllers/line_items_controller.rb
def create
  # Find associated product and current cart
  chosen_product = Product.find(params[:product_id])
  current_cart = @current_cart

  # If cart already has this product then find the relevant line_item and iterate quantity otherwise create a new line_item for this product
  if current_cart.products.include?(chosen_product)
    # Find the line_item with the chosen_product
    @line_item = current_cart.line_items.find_by(:product_id => chosen_product)
    # Iterate the line_item's quantity by one
    @line_item.quantity += 1
  else
    @line_item = LineItem.new
    @line_item.cart = current_cart
    @line_item.product = chosen_product
  end

  # Save and redirect to cart show path
  @line_item.save
  redirect_to cart_path(current_cart)
end
def destroy
  @line_item = LineItem.find(params[:id])
  @line_item.destroy
  redirect_to cart_path(@current_cart)
end 
def add_quantity
  @line_item = LineItem.find(params[:id])
  @line_item.quantity += 1
  @line_item.save
  redirect_to cart_path(@current_cart)
end

def reduce_quantity
  @line_item = LineItem.find(params[:id])
  if @line_item.quantity > 1
    @line_item.quantity -= 1
  end
  @line_item.save
  redirect_to cart_path(@current_cart)
end


private
  def line_item_params
    params.require(:line_item).permit(:quantity,:product_id, :cart_id)
  end
  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :find_product, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!,except:[:index]

    def index
      @products = Product.all.order(created_at: :desc)
      
      #@posts = Post.description
    end
    
    def new 
      @product = Product.new
    end
    
    def create
      @product = Product.new(product_params)

      if @product.save
        redirect_to products_path 
      else
        render "new"
      end
    end

    def show
      @product = Product.find(params[:id])
    end

    def find_product
      @product = Product.find(params[:id])
    end

    def edit
      @product = Product.find(params[:id])
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_path
    end

    def update
      @product = Product.find(params[:id])  
      if @product.update(product_params)
        redirect_to products_path
      else
        render 'edit'
      end
    end

   private
    def product_params
      params.require(:product).permit(:name, :price, :description, :photo)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :find_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
   
  end

  def show
    @profile = Profile.find(profile_params)
  end


  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)
  end

  private

  def find_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.permit(:profile).permit(:name, :summary, :birthday, :user_id)
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/electronics_helper.rb
module ElectronicsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/carts/index.html.erb
<h1>Add to Cart</h1>
<!DOCTYPE html>
<html>
<body>

<p>
An image as a link: <a href="https://www.w3schools.com">
<img border="0" alt="W3Schools" src="logo_w3s.gif" width="100" height="100">
</a>
</p>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  </br>
  <div class="form-group">
     <%= f.text_area :name, class:'form-control', placeholder:' Product Name...', id: "exampleTextarea", rows: "3" %>
  </div>
  <div class="form-group">
     <%= f.text_area :description, class:'form-control', placeholder:' Product Description...', id: "exampleTextarea", rows: "3" %>
  </div>
    <div class="form-group">
     <%= f.text_area :price, class:'form-control', placeholder:' Price here..', id: "exampleTextarea", rows: "3" %>
  </div>
  <div class="form-group clearfix">
    <%= f.file_field :photo, id:'uploadimage', class: 'form-control', style: 'width: 29%;
    float: right;' %>
  </div>
 </br>
  <div class="form-group clearfix">
    <%= f.submit id:'', class: 'btn btn-primary btn-lg float-end' %>
  </div>
<% end %>

app/views/products/_lists.html.erb
<% @products.each do |product| %>
<br />
<%= render 'product', product: product %>
<% end %>

app/views/products/_product.html.erb
<div class="card shadow-sm">
  <%= image_tag url_for(product.photo) if product.photo.attached? %>
  <div class="card-body">
    <p class="card-text"><%= product.description %></p>
    <div class="d-flex justify-content-between align-items-center">
    <div class="btn-group">
      <%= link_to "Edit", edit_product_path(product), :remote => true  , class: "btn btn-sm btn-outline-secondary" %>
      <%= button_to 'Delete', product_path(product), method: :delete ,  class:"btn btn-sm btn-outline-secondary" %>
    </div>
    <small class="text-muted"><%=(@product.created_at) %></small>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
 <%= form_with model: @product, method: :patch, local: false do |f| %>
  </br>
  <div class="form-group">
     <%= f.text_area :description, class:'form-control', placeholder:'Tell us more about your project...', id: "exampleTextarea", rows: "3" %>
  </div>
    <div class="form-group">
     <%= f.text_area :price, class:'form-control', placeholder:'Price here...', id: "exampleTextarea", rows: "3" %>
  </div>
  <div class="form-group clearfix">
    <%= f.file_field :photo, id:'uploadimage', class: 'form-control', style: 'width: 9;
    float: right;' %>
  </div>
 </br>
  <div class="form-group clearfix">
    <%= f.submit id:'postbutton', class: 'btn btn-primary btn-lg float-end' %>
  </div>
<% end %>

app/views/products/index.html.erb
<h2>All Products</h2>
<%= link_to "New product", new_product_path %>
<% @products.each do |product| %>
  <p>Name: <%= product.name %><br>
    Description: <%= product.description %><br>
    unit price of <%= number_to_currency(product.price) %>
    <%= image_tag url_for(product.photo) if product.photo.attached? %>
    <%= product.photo %></p>
  <p>
    <%= link_to "Edit", edit_product_path(product) %>
    <%= button_to "Delete", product_path(product), method: :delete, data: {confirm: "Are you sure?"} %>
    <%#= link_to "Add #{product.name} to cart", line_items_path(:product_id => product.id) %>
    <%= link_to "Add to cart", carts_path() %>
    <%= link_to "Buy #{product.name} now", cart_path(:products) %>
  <%#= link_to "Add to Cart", line_items_path(:product_id => product), :method => :post %>
  </p>
<% end %>
<!-- <%= button_to "Add to cart", line_items_path(:products) %> -->

app/views/products/new.html.erb
New products 
<%= render 'form'%>
<%#= render 'lists'%>

app/views/products/show.html.erb
<h1>Show product</h1>